# Generated by Django 3.2 on 2021-04-27 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('idEtudiant', models.AutoField(primary_key=True, serialize=False)),
                ('cin', models.CharField(default='', max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('birthDate', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('idQuestion', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(max_length=255)),
                ('questionKey', models.CharField(max_length=100)),
                ('dateQuestion', models.CharField(max_length=50)),
                ('image', models.CharField(default='', max_length=100)),
                ('idEtudiant', models.ForeignKey(db_constraint=False, default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='EtudiantApp.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('idComment', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(default='', max_length=255)),
                ('dateComment', models.CharField(max_length=50)),
                ('idEtudiant', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='EtudiantApp.etudiant')),
                ('idQuestion', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='EtudiantApp.question')),
            ],
        ),
    ]
