# Generated by Django 3.2 on 2021-05-18 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('idMessage', models.AutoField(primary_key=True, serialize=False)),
                ('fullnameS', models.CharField(max_length=100)),
                ('idEtudiantR', models.IntegerField(default=0)),
                ('fullnameR', models.CharField(max_length=100)),
                ('message', models.TextField(default='', max_length=255)),
                ('seen', models.BooleanField(default=False)),
                ('idEtudiantS', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='EtudiantApp.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Exercices',
            fields=[
                ('ExerciceId', models.AutoField(primary_key=True, serialize=False)),
                ('ExerciceName', models.CharField(max_length=100)),
                ('ExerciceDescri', models.CharField(default='', max_length=100)),
                ('ExerciceLevel', models.CharField(max_length=100)),
                ('ExerciceDate', models.CharField(default='', max_length=100)),
                ('PhotoFileName', models.CharField(max_length=100)),
                ('idEtudiant', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='EtudiantApp.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('CoursId', models.AutoField(primary_key=True, serialize=False)),
                ('CoursName', models.CharField(max_length=100)),
                ('CoursDescri', models.CharField(default='', max_length=100)),
                ('CoursLevel', models.CharField(max_length=100)),
                ('CoursDate', models.CharField(default='', max_length=100)),
                ('PhotoFileName', models.CharField(max_length=100)),
                ('idEtudiant', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='EtudiantApp.etudiant')),
            ],
        ),
    ]
