# Generated by Django 3.2 on 2021-06-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0002_courses_exercices_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formations',
            fields=[
                ('FormationId', models.AutoField(primary_key=True, serialize=False)),
                ('FormationName', models.CharField(max_length=200)),
                ('FormationDiscription', models.CharField(max_length=200)),
            ],
        ),
    ]
