# Generated by Django 3.2 on 2021-06-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtudiantApp', '0003_formations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('idEnseignant', models.AutoField(primary_key=True, serialize=False)),
                ('cin', models.CharField(default='', max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('birthDate', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Formations',
        ),
        migrations.RemoveField(
            model_name='exercices',
            name='ExerciceDescri',
        ),
        migrations.AlterField(
            model_name='exercices',
            name='idEtudiant',
            field=models.IntegerField(),
        ),
    ]
